spring:
  application:
    name: yxmall_platform
  profiles:
    active: prod
  jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss
server:
  port: 8088

# Logger Config
logging:
  level:
    com.yxmall: debug

mybatis-plus:
  type-aliases-package: com.yxmall.platform.*.entity
  mapper-locations: classpath*:mapper/*.xml

security:
  ignore:
    urls:
    - /code/*
    - /druid/**
    - /swagger-ui.html
    - /swagger-resources/**
    - /swagger/**
    - /**/v2/api-docs
    - /**/*.js
    - /**/*.css
    - /**/*.png
    - /**/*.ico
    - /test