spring:
  application:
    name: yxmall_platform
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/yxmall_platform?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-test-query: SELECT 1 FROM DUAL

server:
  port: 8088

# Logger Config
logging:
  level:
    com.smile: debug

mybatis-plus:
  type-aliases-package: com.smile.yx.platform.entity
  mapper-locations: classpath*:mapper/*.xml



