spring:
  application:
    name: yxmall_platform
  profiles:
    active: dev

server:
  port: 8088

# Logger Config
logging:
  level:
    com.smile: debug

mybatis-plus:
  type-aliases-package: com.smile.yx.platform.entity
  mapper-locations: classpath*:mapper/*.xml
