spring:
  application:
    name: yxmall_platform
  profiles:
    active: prod
  redis:
    database: 0
    host: 111.230.46.97
    port: 6379
    password: wang1993qing1998++.
    timeout: 90
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
server:
  port: 8088

# Logger Config
logging:
  level:
    com.smile: debug

mybatis-plus:
  type-aliases-package: com.smile.yx.platform.entity
  mapper-locations: classpath*:mapper/*.xml






